Add a "copy button".
swapagarwal/geeksay pull request #357
Opened 2022-09-19 13:41 UTC by abitsalihu

I added a "copy button" so when the user clicks on that button the translated quote will be copied to our clipboard!

Below is a video of how this button will work:

https://user-images.githubusercontent.com/94648837/191030880-4ce56884-6c27-4b76-b1a1-8f80d4bbae32.mov

2022-09-21 06:08 UTC, dk3775 requested changes
I think that code changes on lines 420,421 are unnecessary please check and confirm.

Also please remove extra spaces!

2022-09-21 07:30 UTC, dk3775 commented
Also give a js alert which says copied successfully.

2022-09-21 09:29 UTC, abitsalihu commented
@dk3775, I removed the unnecessary code, and added the alert that the quote was copied successfully.

2022-09-22 02:08 UTC, dk3775 approved these changes

2022-09-22 02:08 UTC, merged